### ISSUE TITLE
Fixed map plot areas in 3.11.0

### ISSUE THREAD

**Issue by ewhelan** [Hirlam/obsmon#6]
Hi Paulo,

I hope you are still supporting 3.11.0!

In 3.3.2 I fixed map plot area with the following in src/plots/plots_maps.R with the following:

`#EOIN  x1 <- min(plotData$longitude)-2`
`#EOIN  x2 <- max(plotData$longitude)+2`
`#EOIN  y1 <- min(plotData$latitude)-2`
`#EOIN  y2 <- max(plotData$latitude)+2`
 ` x1 <- -35`
`  x2 <- 5`
`  y1 <- 45`
`  y2 <- 65`
This doesn't seem to work in 3.11.0. Do you have any insight?

**Comment by paulovcmedeiros** [comment]
Hi Eoin,

I'm not really supporting v3.11.0... I changed quite a lot of stuff related to the used R-packages. My guess is that something changed in the plotting libraries (maybe ggplot2 or plotly), but this is just a guess.

My advice would be for you to upgrade and try your fix in the new version.

I'm gonna close this since this is not really an issue (your fix is quite specific to the area you want to cover, and one can always pan, zoom in and out of the maps to select a different area).

**Comment by ewhelan** [comment]
Thanks Paulo.

Hacked the plotly geo specification to sort this.

Will brave v4.X soon!

Eoin
